services:
  weather-cep-api:
    build: .
    container_name: weather-cep-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - zipkin

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
