services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=${APP_PORT}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
